DOMAIN = "fmc130_traccar"

# Device Config
CONF_IMEI = "imei"
CONF_DEVICE_NAME = "device_name"

# Direct Listener Config
CONF_LISTENER_PORT = "listener_port"
CONF_TLS_ENABLED = "tls_enabled"
CONF_TLS_MODE = "tls_mode"
CONF_SSL_CERT = "ssl_cert"
CONF_SSL_KEY = "ssl_key"
CONF_DEBUG_MODE = "debug_mode"

TLS_MODE_NONE = "none"
TLS_MODE_HA = "home_assistant"
TLS_MODE_CUSTOM = "custom"

DEFAULT_PORT = 8082
DEFAULT_LISTENER_PORT = 5027
DEFAULT_USE_SSL = True

CONF_MAPPING_RPM = "map_rpm"
CONF_MODIFIER_RPM = "mod_rpm"
CONF_MAPPING_FUEL = "map_fuel"
CONF_MODIFIER_FUEL = "mod_fuel"
CONF_MAPPING_OIL = "map_oil"
CONF_MODIFIER_OIL = "mod_oil"
CONF_MAPPING_DTC = "map_dtc"
CONF_MODIFIER_DTC = "mod_dtc"

CONF_MAPPING_DOOR_FL = "map_door_fl"
CONF_MODIFIER_DOOR_FL = "mod_door_fl"
CONF_MAPPING_DOOR_FR = "map_door_fr"
CONF_MODIFIER_DOOR_FR = "mod_door_fr"
CONF_MAPPING_DOOR_RL = "map_door_rl"
CONF_MODIFIER_DOOR_RL = "mod_door_rl"
CONF_MAPPING_DOOR_RR = "map_door_rr"
CONF_MODIFIER_DOOR_RR = "mod_door_rr"
CONF_MAPPING_LOCKED = "map_locked"
CONF_MODIFIER_LOCKED = "mod_locked"
CONF_MAPPING_WINDOWS = "map_windows"
CONF_MODIFIER_WINDOWS = "mod_windows"
CONF_MAPPING_HANDBRAKE = "map_handbrake"
CONF_MODIFIER_HANDBRAKE = "mod_handbrake"
CONF_MAPPING_LIGHTS = "map_lights"
CONF_MODIFIER_LIGHTS = "mod_lights"

# New mappings to standardize all IOs
CONF_MAPPING_VOLTAGE = "map_voltage"
CONF_MODIFIER_VOLTAGE = "mod_voltage"
CONF_MAPPING_SPEED = "map_speed"
CONF_MODIFIER_SPEED = "mod_speed"
CONF_MAPPING_MILEAGE = "map_mileage"
CONF_MODIFIER_MILEAGE = "mod_mileage"
CONF_MAPPING_ENGINE_TEMP = "map_engine_temp"
CONF_MODIFIER_ENGINE_TEMP = "mod_engine_temp"
CONF_MAPPING_SLEEP_MODE = "map_sleep_mode"
CONF_MODIFIER_SLEEP_MODE = "mod_sleep_mode"
CONF_MAPPING_IGNITION = "map_ignition"
CONF_MODIFIER_IGNITION = "mod_ignition"
CONF_MAPPING_MOTION = "map_motion"
CONF_MODIFIER_MOTION = "mod_motion"
CONF_MAPPING_TRUNK = "map_trunk"
CONF_MODIFIER_TRUNK = "mod_trunk"
CONF_MAPPING_VEHICLE_RANGE = "map_vehicle_range"
CONF_MODIFIER_VEHICLE_RANGE = "mod_vehicle_range"
CONF_MAPPING_ENGINE_COVER = "map_engine_cover"
CONF_MODIFIER_ENGINE_COVER = "mod_engine_cover"
CONF_MAPPING_CHECK_ENGINE = "map_check_engine"
CONF_MODIFIER_CHECK_ENGINE = "mod_check_engine"
CONF_MAPPING_COOLANT_LEVEL = "map_coolant_level"
CONF_MODIFIER_COOLANT_LEVEL = "mod_coolant_level"
CONF_MAPPING_BATTERY_CHARGE = "map_battery_charge"
CONF_MODIFIER_BATTERY_CHARGE = "mod_battery_charge"
CONF_MAPPING_WARNING = "map_warning"
CONF_MODIFIER_WARNING = "mod_warning"
CONF_MAPPING_LOW_TIRE = "map_low_tire"
CONF_MODIFIER_LOW_TIRE = "mod_low_tire"
CONF_MAPPING_WEAR_BRAKE = "map_wear_brake"
CONF_MODIFIER_WEAR_BRAKE = "mod_wear_brake"
CONF_MAPPING_LOW_FUEL = "map_low_fuel"
CONF_MODIFIER_LOW_FUEL = "mod_low_fuel"
CONF_MAPPING_MAINTENANCE = "map_maintenance"
CONF_MODIFIER_MAINTENANCE = "mod_maintenance"
CONF_MAPPING_LOW_COOLANT = "map_low_coolant"
CONF_MODIFIER_LOW_COOLANT = "mod_low_coolant"

DEFAULT_MAPPINGS = {
    CONF_MAPPING_RPM: "85",
    CONF_MAPPING_FUEL: "84",
    CONF_MAPPING_OIL: "235",
    CONF_MAPPING_DTC: "282", # Typical DTC IO
    CONF_MAPPING_DOOR_FL: "654",
    CONF_MAPPING_DOOR_FR: "655",
    CONF_MAPPING_DOOR_RL: "656",
    CONF_MAPPING_DOOR_RR: "657",
    CONF_MAPPING_LOCKED: "662",
    CONF_MAPPING_WINDOWS: "", # Varies widely, let user configure if present
    CONF_MAPPING_HANDBRAKE: "653",
    CONF_MAPPING_LIGHTS: "", # Varies widely
    
    CONF_MAPPING_VOLTAGE: "66",
    CONF_MAPPING_SPEED: "81",
    CONF_MAPPING_MILEAGE: "87",
    CONF_MAPPING_ENGINE_TEMP: "115",
    CONF_MAPPING_SLEEP_MODE: "200",
    CONF_MAPPING_IGNITION: "239",
    CONF_MAPPING_MOTION: "240",
    CONF_MAPPING_TRUNK: "658",
    CONF_MAPPING_VEHICLE_RANGE: "866",
    CONF_MAPPING_ENGINE_COVER: "913",
    CONF_MAPPING_CHECK_ENGINE: "953",
    CONF_MAPPING_COOLANT_LEVEL: "959",
    CONF_MAPPING_BATTERY_CHARGE: "960",
    CONF_MAPPING_WARNING: "964",
    CONF_MAPPING_LOW_TIRE: "966",
    CONF_MAPPING_WEAR_BRAKE: "967",
    CONF_MAPPING_LOW_FUEL: "968",
    CONF_MAPPING_MAINTENANCE: "969",
    CONF_MAPPING_LOW_COOLANT: "976",
}

DEFAULT_MODIFIERS = {
    CONF_MODIFIER_RPM: "",
    CONF_MODIFIER_FUEL: "*0.1",
    CONF_MODIFIER_OIL: "",
    CONF_MODIFIER_DTC: "",
    CONF_MODIFIER_DOOR_FL: "",
    CONF_MODIFIER_DOOR_FR: "",
    CONF_MODIFIER_DOOR_RL: "",
    CONF_MODIFIER_DOOR_RR: "",
    CONF_MODIFIER_LOCKED: "",
    CONF_MODIFIER_WINDOWS: "",
    CONF_MODIFIER_HANDBRAKE: "",
    CONF_MODIFIER_LIGHTS: "",
    
    CONF_MODIFIER_VOLTAGE: "*0.001",
    CONF_MODIFIER_SPEED: "",
    CONF_MODIFIER_MILEAGE: "*0.001",
    CONF_MODIFIER_ENGINE_TEMP: "*0.1",
    CONF_MODIFIER_SLEEP_MODE: "",
    CONF_MODIFIER_IGNITION: "",
    CONF_MODIFIER_MOTION: "",
    CONF_MODIFIER_TRUNK: "",
    CONF_MODIFIER_VEHICLE_RANGE: "",
    CONF_MODIFIER_ENGINE_COVER: "",
    CONF_MODIFIER_CHECK_ENGINE: "",
    CONF_MODIFIER_COOLANT_LEVEL: "",
    CONF_MODIFIER_BATTERY_CHARGE: "",
    CONF_MODIFIER_WARNING: "",
    CONF_MODIFIER_LOW_TIRE: "",
    CONF_MODIFIER_WEAR_BRAKE: "",
    CONF_MODIFIER_LOW_FUEL: "",
    CONF_MODIFIER_MAINTENANCE: "",
    CONF_MODIFIER_LOW_COOLANT: "",
}
