# custom_components/fmc130_traccar/services.yaml
lock:
  name: car.lock
  description: Sends a lock command directly to the vehicle.
  fields:
    device_id:
      description: The Home Assistant device ID of the tracker.
      example: "1234567890abcdef"
      required: true
      selector:
        device:
          integration: fmc130_traccar

unlock:
  name: car.unlock
  description: Sends an unlock command directly to the vehicle.
  fields:
    device_id:
      description: The Home Assistant device ID of the tracker.
      example: "1234567890abcdef"
      required: true
      selector:
        device:
          integration: fmc130_traccar

horn:
  name: car.horn
  description: Sends a horn command directly to the vehicle.
  fields:
    device_id:
      description: The Home Assistant device ID of the tracker.
      required: true
      selector:
        device:
          integration: fmc130_traccar

flash_lights:
  name: car.flash_lights
  description: Sends a flash lights command directly to the vehicle.
  fields:
    device_id:
      description: The Home Assistant device ID of the tracker.
      required: true
      selector:
        device:
          integration: fmc130_traccar

engine_start:
  name: car.engine_start
  description: Sends an engine start command directly to the vehicle.
  fields:
    device_id:
      description: The Home Assistant device ID of the tracker.
      required: true
      selector:
        device:
          integration: fmc130_traccar

engine_stop:
  name: car.engine_stop
  description: Sends an engine stop command directly to the vehicle.
  fields:
    device_id:
      description: The Home Assistant device ID of the tracker.
      required: true
      selector:
        device:
          integration: fmc130_traccar

dtc_reset:
  name: car.dtc_reset
  description: Sends a DTC reset command directly to the vehicle.
  fields:
    device_id:
      description: The Home Assistant device ID of the tracker.
      required: true
      selector:
        device:
          integration: fmc130_traccar
